-- ilrathCXV: Reworked to give an initial boost on item use (Surgical Precision * 6%)
local heal_item_boost_time = 0
local radheal_item_boost_time = 0
local bleedheal_item_boost_time = 0
local heal_per_sec = 0
local radheal_per_sec = 0
local bleedheal_per_sec = 0


function get_healing_boost(obj, string)
	
	if x_cxv_perks_data.perks["perk_surgical_precision"] > 0 then
		if SYS_GetParam(0, obj:section(), "kind") == "i_medical" then
			if SYS_GetParam(2, obj:section(), "boost_health_restore") and SYS_GetParam(2, obj:section(), "boost_health_restore") > 0 then
				heal_item_boost_time = SYS_GetParam(2, obj:section(), "boost_time")
				heal_per_sec = SYS_GetParam(2, obj:section(), "boost_health_restore") * 6
				instant_heal = heal_per_sec * (x_cxv_perks_data.perks["perk_surgical_precision"] * 0.06 * heal_item_boost_time)
				db.actor:change_health(instant_heal)
			end
			if SYS_GetParam(2, obj:section(), "boost_radiation_restore") and SYS_GetParam(2, obj:section(), "boost_radiation_restore") > 0 then
				radheal_item_boost_time = SYS_GetParam(2, obj:section(), "boost_time")
				radheal_per_sec = SYS_GetParam(2, obj:section(), "boost_radiation_restore") * 6
				instant_radaway = -(radheal_per_sec * (x_cxv_perks_data.perks["perk_surgical_precision"] * 0.06 * radheal_item_boost_time))
				db.actor:change_radiation(instant_radaway)
			end
			if SYS_GetParam(2, obj:section(), "boost_bleeding_restore") and SYS_GetParam(2, obj:section(), "boost_bleeding_restore") > 0 then
				bleedheal_item_boost_time = SYS_GetParam(2, obj:section(), "boost_time")
				bleedheal_per_sec = SYS_GetParam(2, obj:section(), "boost_bleeding_restore") * 6
				instant_jgut = bleedheal_per_sec * (x_cxv_perks_data.perks["perk_surgical_precision"] * 0.06 * bleedheal_item_boost_time)
				db.actor.bleeding = instant_jgut
			end
	
		end
	end
end

function on_game_start()
    RegisterScriptCallback("actor_on_item_use",         get_healing_boost)
end

-- If using the food poisoning mod, this perk will increase the amount of toxins cured
if food_poisoning then
	BaseFoodPoisonQueue = food_poisoning.add_to_queue
	function food_poisoning.add_to_queue(id, ticks, amt)
		
		if amt > 0 then return BaseFoodPoisonQueue(id, ticks, amt) end
		
		return BaseFoodPoisonQueue(id, ticks, (amt * (1 + (x_cxv_perks_data.perks["perk_surgical_precision"] * 0.06))))
		
		--return true
	end
end