local math_random = math.random

local grenade_list =
{
	"grenade_rgd5",
	"grenade_f1",
	"grenade_gd-05",
	--"grenade_smoke",
	--"ied_throwable",
	"grenade_vog25hattab",
	"grenade_rgn_impact",
	"grenade_rgo_impact",
}

local explosive_weapon_list =
{
	"wpn_rg-6",
	"wpn_rpg7",
	"wpn_m79"
}

local function create_item(i, box)
    local se_item = alife_create_item(i, box)
	if not se_item then
		printf("[RPG Crash Catch - EP] This explosive weaponry does not exist: %s", i)
		return
	end
	alife_create_item(i, box)
end

BaseNPCLoadout = xrs_rnd_npc_loadout.on_creation
function xrs_rnd_npc_loadout.on_creation(se_npc)
	if not (se_npc) then
		return
	end
	
	if xrs_rnd_npc_loadout.skip_npc and xrs_rnd_npc_loadout.skip_npc[se_npc:section_name()] then
		xrs_rnd_npc_loadout.print_debug("NPC Loadouts | SKIP | %s", se_npc:section_name())
		return
	end
	
	BaseNPCLoadout(se_npc)
	if x_cxv_perks_data.perks["perk_demo_expert"] > 0 then
		if IsStalker(npc) then
			if math_random(100) < math_random(x_cxv_perks_data.perks["perk_demo_expert"] * 10) then
				create_item(grenade_list[math_random(#grenade_list)], se_npc)
			end
			if x_cxv_perks_data.perks["perk_demo_expert"] == 3 then
				if math_random(10000) == 1 then
					create_item(explosive_weapon_list[math_random(#explosive_weapon_list)], se_npc)
				end
			end
		end
	end
	
end