local reload_bonuses = {[0] = 0, [1] = 10, [2] = 20, [3] = 35, [4] = 50, [5] = 75}

local reload_anims = {
	anm_reload = true,
	anm_reload_1 = true,
	anm_reload_2 = true,
	anm_reload_empty = true,
	anm_reload_empty_variant1 = true,
	anm_reload_empty_variant2 = true,
	anm_add_cartridge = true,
	anm_add_cartridge_empty = true,
	anm_add_cartridge_variant1 = true,
	anm_add_cartridge_variant2 = true,
	anm_add_cartridge_variant3 = true,
	anm_add_cartridge_variant4 = true,
	anm_add_cartridge_empty_variant1 = true,
	anm_add_cartridge_empty_variant2 = true,
	anm_add_cartridge_empty_variant3 = true,
	anm_add_cartridge_empty_variant4 = true,
	anm_close = true,
	anm_open = true,
	anm_open_empty = true,
	anm_reload_g = true,
	anm_reload_w_gl = true,
	anm_reload_empty_w_gl = true,
	anm_reload_ammo5 = true,
	anm_reload_ammo5_variant1 = true,
	anm_reload_ammo5_variant2 = true,
	anm_reload_ammo5_variant3 = true,
	anm_reload_ammo5_variant4 = true,
	anm_reload_ammo5_variant5 = true,
	anm_reload_ammo4 = true,
	anm_reload_ammo4_variant1 = true,
	anm_reload_ammo4_variant2 = true,
	anm_reload_ammo4_variant3 = true,
	anm_reload_ammo3 = true,
	anm_reload_ammo3_variant1 = true,
	anm_reload_ammo3_variant2 = true,
	anm_reload_ammo2 = true,
	anm_reload_ammo2_variant1 = true,
	anm_reload_ammo2_variant2 = true,
	anm_reload_ammo2_variant3 = true,
	anm_reload_ammo1 = true,
	anm_reload_ammo1_variant1 = true,
	anm_reload_ammo1_variant2 = true,
	anm_reload_ammo1_variant3 = true,
	anm_reload_ammo1_variant4 = true,
	anm_reload_ammo1_variant5 = true,
}

function actor_on_hud_animation_play(anim_table,obj)
	if (not IsWeapon(obj)) then return end
	
	local anm_name = anim_table.anm_name
	-- printf("[Rapid Reload] Animation Name: %s", anm_name)
	
	if obj:parent() and obj:parent():id() ~= AC_ID then return end
	
	if (x_cxv_perks_data.perks["perk_rapid_reload"] < 1) and (x_cxv_perks_data.perks["perk_zone_slayer"] < 1) and (x_cxv_perks_data.perks["perk_wick_mode"] < 1) then return end

	if not reload_anims[anm_name] then return end

	local reload_string = tostring(anm_name)
	local wpn_sec = obj:section()
	local hud_sec = ini_sys:r_string_ex(wpn_sec,"hud")
	
	local reload_val = parse_list(ini_sys,hud_sec,reload_string)

	local animation_speed = anim_table.anm_speed
	for k, v in pairs(reload_val) do
		if tonumber(v) then
			animation_speed = tonumber(v)
			break
		end
	end
	
	local zone_slayer_bonus = 0
	local wick_mode_bonus = 0
	
	local wick_slayer_reload = x_cxv_perks_mcm.get_config("wick_slayer_reload") or false
	
	if wick_slayer_reload then
	
		if x_cxv_perks_data.perks["perk_zone_slayer"] > 0 and #x_cxv_perks_data.shotgun_list > 0 then
			for i = 1, #x_cxv_perks_data.shotgun_list do
				if x_cxv_perks_data.shotgun_list[i] then
					local weapon_from_list = x_cxv_perks_data.shotgun_list[i]
					printf("[RR] Weapon: %s", weapon_from_list)
					if weapon_from_list:section() == wpn_sec then
						zone_slayer_bonus = 0.30
						break
					end
				end
			end
		end
		
		
		if x_cxv_perks_data.perks["perk_wick_mode"] > 0 then
			wpn_kind = x_cxv_perks_data.sortK_of(obj)
			if wpn_kind == "pistol" then
				wick_mode_bonus = 0.30
			elseif wpn_kind ~= "melee" and wpn_kind ~= "explosive" and wpn_kind ~= "misc" and wpn_kind ~= "heavy" then
				if SYS_GetParam(2, obj:section(), "single_handed") == 1 then
					wick_mode_bonus = 0.30
				end
			end
		end
	
	end
	
	anim_table.anm_speed = animation_speed * (1 + (reload_bonuses[x_cxv_perks_data.perks["perk_rapid_reload"]] * 0.01) + zone_slayer_bonus + wick_mode_bonus)
	
end

function on_game_start()
	--[NEW] Reload Speed
	RegisterScriptCallback("actor_on_hud_animation_play", actor_on_hud_animation_play)
end
