local task_ini = ini_file("misc\\task\\task_manager.ltx")
task_item_list = {}	-- .count, .chance

item_chance_floor =  0.01 -- 0.005

invalid_kinds = {
	["w_pistol"] = false,
	["w_smg"] = false,
	["w_shotgun"] = false,
	["w_melee"] = false,
	
	["i_quest"] = true,
	["w_rifle"] = true,
	["w_sniper"] = true,
	["w_explosive"] = true,
	["w_heavy"] = true
}

damaged_kinds = {
	["i_arty"] = true,
	["i_arty_cont"] = true,
	["i_arty_junk"] = true,
	["i_mutant_belt"] = true,
	["w_pistol"] = true,
	["w_shotgun"] = true,
	["w_melee"] = true,
	["w_smg"] = true,
	["w_rifle"] = true,
	["w_sniper"] = true,
	["w_heavy"] = true
}

blacklisted_sections = {
	["itm_basickit"] = true,
	["itm_advancedkit"] = true,
	["itm_expertkit"] = true,
	["itm_drugkit"] = true,
	["itm_ammokit"] = true,
	["device_pda_2"] = true,
	["device_pda_3"] = true,
	["detector_advanced"] = true,
	["detector_elite"] = true,
	["detector_scientific"] = true,
	["detector_anomaly"] = true,
	["detector_grizzly"] = true,
	["device_pda_milspec"] = true
}

function valid_fetch_loot(sec)
	if not sec then return false end

	local kind = SYS_GetParam(0, sec, "kind")
	
	if invalid_kinds[kind] then return false end
	
	return true
end

function get_task_items()
	local actor = db.actor
	if not actor then return end
	
	empty_table(task_item_list)
	task_item_list = {}
	
	if (x_cxv_perks_data.perks["perk_fetch_finder"] < 1) then return end
	
	local tm = task_manager.get_task_manager()
	local task_info = tm.task_info
	
	for task_id,v in pairs(task_info) do
		local status = task_info[task_id].last_check_task
		if not (status == "complete" or status == "fail") then 
	
			-- Fetch
			local fetch_sec = load_var(actor, task_id.."_fetch")
			if fetch_sec and (not blacklisted_sections[fetch_sec]) and valid_fetch_loot(fetch_sec) then
				calculate_fetch_finder_data(fetch_sec, true)
--				printf("[RPG - Fetch Finder] Task Item being added to list: %s", fetch_sec, task_item_list[fetch_sec])
			end
	
			-- Multi fetch
			check_multifetch_items(task_id, true)
		end
	end
end

function check_multifetch_items(task_id, is_adding)

	local _M
	_M = _M or alife_storage_manager.get_state().multifetch_data
	
	local required_items = _M and _M[task_id] and _M[task_id].required_items
	if required_items then
		for k,v in pairs(required_items) do
			local sec = required_items[k].sec
			if sec and (not blacklisted_sections[sec]) and valid_fetch_loot(sec) then
				calculate_fetch_finder_data(sec, is_adding)
--				printf("[RPG - Fetch Finder] Task Item being assesed: %s | Is adding?: %s | Count: %s", sec, is_adding, task_item_list[sec] and task_item_list[sec].count or 0)
			end
		end
	end
	local optional_items = _M and _M[task_id] and _M[task_id].optional_items
	if optional_items then
		for k,v in pairs(optional_items) do
			local sec = optional_items[k].sec
			if sec and (not blacklisted_sections[sec]) and valid_fetch_loot(sec) then
				calculate_fetch_finder_data(sec, is_adding)
--				printf("[RPG - Fetch Finder] Task Item being assesed: %s | Is adding?: %s | Count: %s", sec, is_adding, task_item_list[sec] and task_item_list[sec].count or 0)
			end
		end
	end
end

OrigGiveTask = task_manager.CRandomTask.give_task
task_manager.CRandomTask.give_task = function(self,task_id,task_giver_id)
	
	OrigGiveTask(self,task_id,task_giver_id)

	if (x_cxv_perks_data.perks["perk_fetch_finder"] < 1) then return end
	
	-- Increment task item in list
	local check_fetch_quest_sec = load_var(db.actor, task_id.."_fetch")
	if check_fetch_quest_sec and (not blacklisted_sections[check_fetch_quest_sec]) and valid_fetch_loot(check_fetch_quest_sec) then
		calculate_fetch_finder_data(check_fetch_quest_sec, true)
--		printf("[RPG - Fetch Finder] Task Item being added to list: %s", check_fetch_quest_sec)
	end
	
	check_multifetch_items(task_id, true)
	
end

OrigCompleteTask = task_manager.CRandomTask.set_task_completed
task_manager.CRandomTask.set_task_completed = function(self, task_id)
	if (self.task_info[task_id]) then
		-- Decrement items from the fetch list
		if (x_cxv_perks_data.perks["perk_fetch_finder"] > 0) then
			local check_fetch_quest_sec = load_var(db.actor, task_id.."_fetch")
			if check_fetch_quest_sec and task_item_list[check_fetch_quest_sec] then
				calculate_fetch_finder_data(check_fetch_quest_sec, false)
--				printf("[RPG] Task Item being removed to list: %s", check_fetch_quest_sec)
			end
			check_multifetch_items(task_id, false)
		end
		
		self.task_info[task_id].forced_status = "complete"
	end
end

OrigFailTask = task_manager.CRandomTask.set_task_failed
task_manager.CRandomTask.set_task_failed = function(self, task_id)
	if (self.task_info[task_id]) then
		
		-- Decrement items from the fetch list
		if (x_cxv_perks_data.perks["perk_fetch_finder"] > 0) then
			local check_fetch_quest_sec = load_var(db.actor, task_id.."_fetch")
			if check_fetch_quest_sec and task_item_list[check_fetch_quest_sec] then
				calculate_fetch_finder_data(check_fetch_quest_sec, false)
--				printf("[RPG] Task Item being removed to list: %s", check_fetch_quest_sec)
			end
			check_multifetch_items(task_id, false)
		end
		
		self.task_info[task_id].forced_status = "fail"
	end
end

OrigCancelTask = task_manager.CRandomTask.set_task_cancelled
task_manager.CRandomTask.set_task_cancelled = function(self, task_id)
    if (self.task_info[task_id]) then
		
		-- Decrement items from the fetch list
		if (x_cxv_perks_data.perks["perk_fetch_finder"] > 0) then
			local check_fetch_quest_sec = load_var(db.actor, task_id.."_fetch")
			if check_fetch_quest_sec and task_item_list[check_fetch_quest_sec] then
				calculate_fetch_finder_data(check_fetch_quest_sec, false)
--				printf("[RPG - Fetch Finder] Task Item being decremented: %s", check_fetch_quest_sec)
			end
			check_multifetch_items(task_id, false)
		end
		
		self.task_info[task_id].forced_status = "fail"
		self.task_info[task_id].cancelled_by_actor = true
    end
end

local function experience_skill_on_update(perk_id, perk_data)
	if perk_id == "perk_fetch_finder" and perk_data["curr_level"] > 0 and is_empty(task_item_list) then
		get_task_items()
	end
end

-- helper function to select an item for the chance
function get_fetch_finder_item(chance, is_stash)
	local possible_items_list = {}
	for k, v in pairs(task_item_list) do
		local item_chance = v.chance
		item_chance = (is_stash and (item_chance * 5)) or item_chance
--		printf("[RPG - Fetch Finder] Item being checked: %s | Item chance: %s", k, item_chance)
		if chance <= item_chance then
			printf("[RPG - Fetch Finder] Item being added to possible loot list: %s | Item chance: %s", k, item_chance)
			possible_items_list[k] = true
		end
	end
	if not is_empty(possible_items_list) then
		local task_item = random_key_table(possible_items_list)
		printf("[RPG - Fetch Finder] Item selected: %s", task_item)
		return task_item
	else
		printf("[RPG - Fetch Finder] No items succeeded chance roll")
		return nil
	end
	
	return nil
end

function get_fetch_finder_data(sec)
	return (task_item_list[sec] and task_item_list[sec]) or nil
end

function calculate_fetch_finder_data(sec, is_adding)
	if task_item_list[sec] and task_item_list[sec].count then
		if is_adding then
			task_item_list[sec].count = task_item_list[sec].count + 1
			calculate_fetch_finder_chance(sec)
		else
			task_item_list[sec].count = task_item_list[sec].count - 1
			if task_item_list[sec].count <= 0 then
				task_item_list[sec] = nil
			else
				calculate_fetch_finder_chance(sec)
			end
		end
	else
		if is_adding then
			task_item_list[sec] = {count = 1, chance = 0}
			calculate_fetch_finder_chance(sec)
		end
	end
end

function calculate_fetch_finder_chance(sec)
	local count = task_item_list[sec] and task_item_list[sec].count or 0
	if count <= 0 then
		printf("[RPG - Fetch Finder] Item (%s) has no count/does not exist in task list - skipping", sec)
		return
	end
	
	local base_cost = ini_sys:r_float_ex(sec,"cost")
	local chance = 0.1
	
	if count > 1 then
		chance = chance * (1 + (0.33 * (count - 1)))
	end
	if base_cost > 500 then
		local chance_adj = 1 - ((2.718)^(-(500/base_cost)))
		chance = math.max( (chance * chance_adj) , item_chance_floor)
	end
	
	printf("[RPG - Fetch Finder] Fetch item cost: %s | Fetch item count: %s | Fetch item final chance: %s", base_cost, count, round_idp(chance, 5))
	
	-- REMEMBER TO MULTIPLY CHANCE BY 2 IF IN A STASH IN LOOTING SCRIPT	
	task_item_list[sec].chance = round_idp(chance, 5)
end

function on_game_start()
	RegisterScriptCallback("actor_on_first_update", 		get_task_items)
	if experience_potions then
		RegisterScriptCallback("experience_skill_on_update", experience_skill_on_update)
	else
		RegisterScriptCallback("experience_perk_on_update", experience_skill_on_update)
	end
end

local location_ranks = {
	["k00_marsh"] = "trainee",
	["l01_escape"] = "novice",
	["l02_garbage"] = "trainee",
	["y04_pole"] = "novice",
	["l05_bar"] = "trainee",
	["l03_agroprom"] = "trainee",
	["k01_darkscape"] = "experienced",
	["l04_darkvalley"] = "trainee",
	["k02_trucks_cemetery"] = "experienced",
	["l06_rostok"] = "trainee",
	["l07_military"] = "experienced",
	["l09_deadcity"] = "trainee",
	["l08_yantar"] = "trainee",
	["l03u_agr_underground"] = "experienced",
	["jupiter"] = "professional",
	["l10_limansk"] = "professional",
	["l04u_labx18"] = "professional",
	["l10_red_forest"] = "professional",
	["l08u_brainlab"] = "experienced",
	["l10_radar"] = "professional",
	["l10u_bunker"] = "veteran",
	["l11_hospital"] = "veteran",
	["l12_stancia"] = "expert",
	["l12_stancia_2"] = "expert",
	["l12u_control_monolith"] = "master",
	["l12u_sarcofag"] = "master",
	["l13_generators"] = "legend",
	["l13u_warlab"] = "legend",
	["labx8"] = "experienced",
	["pripyat"] = "veteran",
	["grimwood"] = "experienced",
	["promzona"] = "experienced",
	["poselok_ug"] = "veteran",
	["bunker_a1"] = "veteran",
	["collaider"] = "veteran",
	["l11_pripyat"] = "veteran"
}

-- Needed for weapon drops for Fetch Finder
BaseObjRank = ranks.get_obj_rank_name
function ranks.get_obj_rank_name( obj )
	if obj and IsInvbox(obj) then
		local level_name = level.name()
		if level_name and location_ranks[level_name] then
			return location_ranks[level_name]
		else
			return "trainee"
		end
	end
	
	return BaseObjRank( obj )
end